// Generated by gencpp from file bb8_custom/bb_msg.msg
// DO NOT EDIT!


#ifndef BB8_CUSTOM_MESSAGE_BB_MSG_H
#define BB8_CUSTOM_MESSAGE_BB_MSG_H

#include <ros/service_traits.h>


#include <bb8_custom/bb_msgRequest.h>
#include <bb8_custom/bb_msgResponse.h>


namespace bb8_custom
{

struct bb_msg
{

typedef bb_msgRequest Request;
typedef bb_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bb_msg
} // namespace bb8_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bb8_custom::bb_msg > {
  static const char* value()
  {
    return "b92c952a9248b3029cefe45f52f6ffde";
  }

  static const char* value(const ::bb8_custom::bb_msg&) { return value(); }
};

template<>
struct DataType< ::bb8_custom::bb_msg > {
  static const char* value()
  {
    return "bb8_custom/bb_msg";
  }

  static const char* value(const ::bb8_custom::bb_msg&) { return value(); }
};


// service_traits::MD5Sum< ::bb8_custom::bb_msgRequest> should match 
// service_traits::MD5Sum< ::bb8_custom::bb_msg > 
template<>
struct MD5Sum< ::bb8_custom::bb_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_custom::bb_msg >::value();
  }
  static const char* value(const ::bb8_custom::bb_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_custom::bb_msgRequest> should match 
// service_traits::DataType< ::bb8_custom::bb_msg > 
template<>
struct DataType< ::bb8_custom::bb_msgRequest>
{
  static const char* value()
  {
    return DataType< ::bb8_custom::bb_msg >::value();
  }
  static const char* value(const ::bb8_custom::bb_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bb8_custom::bb_msgResponse> should match 
// service_traits::MD5Sum< ::bb8_custom::bb_msg > 
template<>
struct MD5Sum< ::bb8_custom::bb_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_custom::bb_msg >::value();
  }
  static const char* value(const ::bb8_custom::bb_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_custom::bb_msgResponse> should match 
// service_traits::DataType< ::bb8_custom::bb_msg > 
template<>
struct DataType< ::bb8_custom::bb_msgResponse>
{
  static const char* value()
  {
    return DataType< ::bb8_custom::bb_msg >::value();
  }
  static const char* value(const ::bb8_custom::bb_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BB8_CUSTOM_MESSAGE_BB_MSG_H
