// Generated by gencpp from file bb8_custom/BB8CustomServiceMessage.msg
// DO NOT EDIT!


#ifndef BB8_CUSTOM_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H
#define BB8_CUSTOM_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <bb8_custom/BB8CustomServiceMessageRequest.h>
#include <bb8_custom/BB8CustomServiceMessageResponse.h>


namespace bb8_custom
{

struct BB8CustomServiceMessage
{

typedef BB8CustomServiceMessageRequest Request;
typedef BB8CustomServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BB8CustomServiceMessage
} // namespace bb8_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bb8_custom::BB8CustomServiceMessage > {
  static const char* value()
  {
    return "b78c0d1a37ffcec6adef7714dda05daa";
  }

  static const char* value(const ::bb8_custom::BB8CustomServiceMessage&) { return value(); }
};

template<>
struct DataType< ::bb8_custom::BB8CustomServiceMessage > {
  static const char* value()
  {
    return "bb8_custom/BB8CustomServiceMessage";
  }

  static const char* value(const ::bb8_custom::BB8CustomServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::bb8_custom::BB8CustomServiceMessageRequest> should match 
// service_traits::MD5Sum< ::bb8_custom::BB8CustomServiceMessage > 
template<>
struct MD5Sum< ::bb8_custom::BB8CustomServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_custom::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::bb8_custom::BB8CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_custom::BB8CustomServiceMessageRequest> should match 
// service_traits::DataType< ::bb8_custom::BB8CustomServiceMessage > 
template<>
struct DataType< ::bb8_custom::BB8CustomServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::bb8_custom::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::bb8_custom::BB8CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bb8_custom::BB8CustomServiceMessageResponse> should match 
// service_traits::MD5Sum< ::bb8_custom::BB8CustomServiceMessage > 
template<>
struct MD5Sum< ::bb8_custom::BB8CustomServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_custom::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::bb8_custom::BB8CustomServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_custom::BB8CustomServiceMessageResponse> should match 
// service_traits::DataType< ::bb8_custom::BB8CustomServiceMessage > 
template<>
struct DataType< ::bb8_custom::BB8CustomServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::bb8_custom::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::bb8_custom::BB8CustomServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BB8_CUSTOM_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H
