// Generated by gencpp from file bb8_custom/BB8CustomServiceMessageRequest.msg
// DO NOT EDIT!


#ifndef BB8_CUSTOM_MESSAGE_BB8CUSTOMSERVICEMESSAGEREQUEST_H
#define BB8_CUSTOM_MESSAGE_BB8CUSTOMSERVICEMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bb8_custom
{
template <class ContainerAllocator>
struct BB8CustomServiceMessageRequest_
{
  typedef BB8CustomServiceMessageRequest_<ContainerAllocator> Type;

  BB8CustomServiceMessageRequest_()
    : side(0.0)
    , repetitions(0)  {
    }
  BB8CustomServiceMessageRequest_(const ContainerAllocator& _alloc)
    : side(0.0)
    , repetitions(0)  {
  (void)_alloc;
    }



   typedef double _side_type;
  _side_type side;

   typedef int32_t _repetitions_type;
  _repetitions_type repetitions;





  typedef boost::shared_ptr< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BB8CustomServiceMessageRequest_

typedef ::bb8_custom::BB8CustomServiceMessageRequest_<std::allocator<void> > BB8CustomServiceMessageRequest;

typedef boost::shared_ptr< ::bb8_custom::BB8CustomServiceMessageRequest > BB8CustomServiceMessageRequestPtr;
typedef boost::shared_ptr< ::bb8_custom::BB8CustomServiceMessageRequest const> BB8CustomServiceMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bb8_custom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2510b5db7c557bb39c17842733f10222";
  }

  static const char* value(const ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2510b5db7c557bb3ULL;
  static const uint64_t static_value2 = 0x9c17842733f10222ULL;
};

template<class ContainerAllocator>
struct DataType< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb8_custom/BB8CustomServiceMessageRequest";
  }

  static const char* value(const ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 side\n\
int32 repetitions\n\
";
  }

  static const char* value(const ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.side);
      stream.next(m.repetitions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BB8CustomServiceMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bb8_custom::BB8CustomServiceMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "side: ";
    Printer<double>::stream(s, indent + "  ", v.side);
    s << indent << "repetitions: ";
    Printer<int32_t>::stream(s, indent + "  ", v.repetitions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BB8_CUSTOM_MESSAGE_BB8CUSTOMSERVICEMESSAGEREQUEST_H
