// Generated by gencpp from file sub_ex/age.msg
// DO NOT EDIT!


#ifndef SUB_EX_MESSAGE_AGE_H
#define SUB_EX_MESSAGE_AGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sub_ex
{
template <class ContainerAllocator>
struct age_
{
  typedef age_<ContainerAllocator> Type;

  age_()
    : years(0.0)
    , months(0.0)
    , days(0.0)  {
    }
  age_(const ContainerAllocator& _alloc)
    : years(0.0)
    , months(0.0)
    , days(0.0)  {
  (void)_alloc;
    }



   typedef float _years_type;
  _years_type years;

   typedef float _months_type;
  _months_type months;

   typedef float _days_type;
  _days_type days;





  typedef boost::shared_ptr< ::sub_ex::age_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sub_ex::age_<ContainerAllocator> const> ConstPtr;

}; // struct age_

typedef ::sub_ex::age_<std::allocator<void> > age;

typedef boost::shared_ptr< ::sub_ex::age > agePtr;
typedef boost::shared_ptr< ::sub_ex::age const> ageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sub_ex::age_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sub_ex::age_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sub_ex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sub_ex': ['/home/user/catkin_ws/src/sub_ex/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sub_ex::age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sub_ex::age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sub_ex::age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sub_ex::age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sub_ex::age_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sub_ex::age_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sub_ex::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8088e290d061dabc94e1feafd4db363";
  }

  static const char* value(const ::sub_ex::age_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8088e290d061dabULL;
  static const uint64_t static_value2 = 0xc94e1feafd4db363ULL;
};

template<class ContainerAllocator>
struct DataType< ::sub_ex::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sub_ex/age";
  }

  static const char* value(const ::sub_ex::age_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sub_ex::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 years\n\
float32 months\n\
float32 days\n\
";
  }

  static const char* value(const ::sub_ex::age_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sub_ex::age_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.years);
      stream.next(m.months);
      stream.next(m.days);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct age_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sub_ex::age_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sub_ex::age_<ContainerAllocator>& v)
  {
    s << indent << "years: ";
    Printer<float>::stream(s, indent + "  ", v.years);
    s << indent << "months: ";
    Printer<float>::stream(s, indent + "  ", v.months);
    s << indent << "days: ";
    Printer<float>::stream(s, indent + "  ", v.days);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUB_EX_MESSAGE_AGE_H
