(cl:defpackage bb8_custom-srv
  (:use )
  (:export
   "BB8CUSTOMSERVICEMESSAGE"
   "<BB8CUSTOMSERVICEMESSAGE-REQUEST>"
   "BB8CUSTOMSERVICEMESSAGE-REQUEST"
   "<BB8CUSTOMSERVICEMESSAGE-RESPONSE>"
   "BB8CUSTOMSERVICEMESSAGE-RESPONSE"
   "BB_MSG"
   "<BB_MSG-REQUEST>"
   "BB_MSG-REQUEST"
   "<BB_MSG-RESPONSE>"
   "BB_MSG-RESPONSE"
  ))

